"""add ig account type and username

Revision ID: 12dbff86b659
Revises: df5cad2c2be2
Create Date: 2026-07-28 11:25:25.825634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12dbff86b659'
down_revision: Union[str, None] = 'df5cad2c2be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('ig_account_type', sa.String(length=32), nullable=True))
    op.add_column('connected_accounts', sa.Column('ig_username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connected_accounts', 'ig_username')
    op.drop_column('connected_accounts', 'ig_account_type')
    # ### end Alembic commands ###
